services:
  amber:
    build: .
    ports:
      - "80:80"
    volumes:
      - /absolute/path/to/your/host/Music:/amber/Music
      - /absolute/path/to/your/host/Staging:/amber/Staging
    environment:
      - AMBER_DUMMY_TOKEN=token_value_here
      - ACOUSTID_API_KEY=api_key_here
